# Auto-generated by KashMakr Dynamic Deploy Adapter
from __future__ import annotations
import sys
import os
import json
import traceback
import inspect
import importlib.util
from pathlib import Path
from typing import Any, Dict
from fastapi import FastAPI, HTTPException, Request
from fastapi.responses import HTMLResponse, JSONResponse
from pydantic import BaseModel, Field

# Ensure deliverable files are on the Python path
ROOT_DIR = Path(__file__).resolve().parent
sys.path.insert(0, str(ROOT_DIR))

app = FastAPI(
    title="KashMakr Verified Deliverable",
    description="Live interactive runtime environment for production deliverable verification.",
    version="1.0.0",
    docs_url="/docs",
    redoc_url="/redoc"
)

MANIFEST = [
  {
    "module": "main",
    "type": "class",
    "name": "AgentState",
    "docstring": "No description provided.",
    "methods": []
  },
  {
    "module": "main",
    "type": "function",
    "name": "get_checkpoint",
    "docstring": "No description provided.",
    "arguments": [
      "session_id"
    ]
  },
  {
    "module": "main",
    "type": "function",
    "name": "save_checkpoint",
    "docstring": "No description provided.",
    "arguments": [
      "session_id",
      "state",
      "metadata"
    ]
  },
  {
    "module": "main",
    "type": "function",
    "name": "tool_logistics_calculator",
    "docstring": "Calculates fuel surcharges, distances, and freight fees dynamically.",
    "arguments": [
      "query"
    ]
  },
  {
    "module": "main",
    "type": "function",
    "name": "tool_financial_ledger_auditor",
    "docstring": "Audits ledger balances and parses payment/transfer amounts.",
    "arguments": [
      "query"
    ]
  },
  {
    "module": "main",
    "type": "function",
    "name": "tool_general_knowledge",
    "docstring": "Fallback knowledge resolution tool.",
    "arguments": [
      "query"
    ]
  },
  {
    "module": "main",
    "type": "function",
    "name": "node_analyze_and_route",
    "docstring": "No description provided.",
    "arguments": [
      "state"
    ]
  },
  {
    "module": "main",
    "type": "function",
    "name": "node_human_in_the_loop_gate",
    "docstring": "Evaluates whether the pending action requires human approval.",
    "arguments": [
      "state"
    ]
  },
  {
    "module": "main",
    "type": "function",
    "name": "run_agent",
    "docstring": "Executes the full dynamic LangGraph workflow with state persistence.",
    "arguments": [
      "prompt",
      "session_id",
      "previous_state"
    ]
  },
  {
    "module": "main",
    "type": "function",
    "name": "approve_action",
    "docstring": "Handles Human-In-The-Loop approval/rejection state transitions.",
    "arguments": [
      "session_id",
      "decision"
    ]
  }
]
RAW_README = """# gig_ec69b0f2

**Type:** code
**Summary:** Code gig executed. 1 Python file(s), Dockerfile included.

## Overview

This is a code gig: a runnable service or script.

## Endpoints / Usage

- No documented endpoints; see code files for details.

## Files

- `requirements.txt` — requirements
- `Dockerfile` — dockerfile
- `main.py` — python
- `README.md` — readme
- `test_app.py` — other

## How to Run

See `runbook.md` for full instructions.

---
Generated by KashMakr."""

class ExecutionRequest(BaseModel):
    module: str = Field(..., description="Name of the module to invoke")
    target: str = Field(..., description="Function or class method to execute")
    payload: Dict[str, Any] = Field(default_factory=dict, description="Keyword arguments for execution")

@app.get("/health")
@app.head("/health")
def health():
    return {"status": "ok", "runtime": "KashMakr Verified Production Engine"}

@app.get("/api/info")
def info():
    return {
        "status": "operational",
        "manifest": MANIFEST,
        "readme_length": len(RAW_README)
    }

HTML_TEMPLATE = r"""<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Verified Deliverable Console</title>
    <script src="https://cdn.tailwindcss.com"></script>
</head>
<body class="bg-slate-50 text-slate-800 antialiased min-h-screen">
    <header class="bg-white border-b border-slate-200 sticky top-0 z-30">
        <div class="max-w-6xl mx-auto px-6 h-16 flex items-center justify-between">
            <div class="flex items-center space-x-3">
                <div class="w-8 h-8 rounded-lg bg-indigo-600 flex items-center justify-center text-white font-bold font-mono">K</div>
                <div>
                    <h1 class="font-bold text-slate-900 text-sm leading-tight">Deliverable Runtime Verification</h1>
                    <span class="text-xs text-emerald-600 font-medium flex items-center gap-1">
                        <span class="w-2 h-2 rounded-full bg-emerald-500 animate-pulse"></span> Production-Ready Deliverable
                    </span>
                </div>
            </div>
            <div class="flex items-center space-x-3">
                <a href="/docs" target="_blank" class="px-3 py-1.5 text-xs font-semibold bg-slate-100 hover:bg-slate-200 text-slate-700 rounded-lg transition-colors border border-slate-200">
                    Interactive Swagger API &rarr;
                </a>
            </div>
        </div>
    </header>

    <main class="max-w-6xl mx-auto px-6 py-8 grid grid-cols-1 lg:grid-cols-12 gap-8">
        <div class="lg:col-span-7 space-y-6">
            <div>
                <h2 class="text-xl font-bold text-slate-900">Delivered Production Capabilities</h2>
                <p class="text-sm text-slate-500">The autonomous agents engineered and validated the following entrypoints for this gig:</p>
            </div>
            <div class="grid grid-cols-1 gap-4">
                __FUNCTIONS_HTML__
            </div>
        </div>

        <div class="lg:col-span-5">
            <div class="bg-white p-6 border border-slate-200 rounded-2xl shadow-xs sticky top-24">
                <h2 class="text-base font-bold text-slate-900 mb-1">Live Execution Sandbox</h2>
                <p class="text-xs text-slate-500 mb-4">Execute endpoints directly against the verified Python codebase.</p>

                <div class="space-y-3">
                    <div>
                        <label class="block text-xs font-semibold text-slate-600 mb-1">Target Module</label>
                        <input id="in_module" type="text" readonly class="w-full px-3 py-2 text-xs bg-slate-50 border border-slate-200 rounded-lg font-mono text-slate-700">
                    </div>
                    <div>
                        <label class="block text-xs font-semibold text-slate-600 mb-1">Callable Function / Class</label>
                        <input id="in_target" type="text" readonly class="w-full px-3 py-2 text-xs bg-slate-50 border border-slate-200 rounded-lg font-mono text-slate-700">
                    </div>
                    <div>
                        <label class="block text-xs font-semibold text-slate-600 mb-1">Input Parameters (JSON payload)</label>
                        <textarea id="in_payload" rows="4" class="w-full px-3 py-2 text-xs font-mono border border-slate-300 rounded-lg focus:ring-2 focus:ring-indigo-500 focus:outline-hidden" placeholder="{}"></textarea>
                    </div>
                    <button id="btn_run" onclick="executeCall()" class="w-full py-2.5 bg-indigo-600 hover:bg-indigo-700 text-white text-xs font-bold rounded-lg shadow-xs transition-colors">
                        Execute Live Code
                    </button>
                </div>

                <div class="mt-4 pt-4 border-t border-slate-100">
                    <label class="block text-xs font-semibold text-slate-600 mb-1">Console Output</label>
                    <pre id="out_response" class="w-full h-44 p-3 bg-slate-900 text-emerald-400 text-xs font-mono rounded-lg overflow-auto">Awaiting execution trigger...</pre>
                </div>
            </div>
        </div>
    </main>

    <script>
        function fillRunner(mod, target, args) {
            document.getElementById('in_module').value = mod;
            document.getElementById('in_target').value = target;
            const dummy = {};
            if (Array.isArray(args)) {
                args.forEach(a => dummy[a] = 0);
            }
            document.getElementById('in_payload').value = JSON.stringify(dummy, null, 2);
            document.getElementById('out_response').innerText = 'Selected ' + mod + '.' + target + '. Ready to run.';
        }

        async function executeCall() {
            const mod = document.getElementById('in_module').value;
            const target = document.getElementById('in_target').value;
            const payloadRaw = document.getElementById('in_payload').value;
            const out = document.getElementById('out_response');

            if (!mod || !target) {
                out.innerText = 'Error: Please select a function from the left list first.';
                return;
            }

            let payload = {};
            try {
                payload = JSON.parse(payloadRaw || '{}');
            } catch(e) {
                out.innerText = 'Error: Invalid JSON payload input.';
                return;
            }

            out.innerText = 'Executing ' + mod + '.' + target + '...';
            try {
                const res = await fetch('/api/execute', {
                    method: 'POST',
                    headers: { 'Content-Type': 'application/json' },
                    body: JSON.stringify({ module: mod, target: target, payload: payload })
                });
                const data = await res.json();
                out.innerText = JSON.stringify(data, null, 2);
            } catch(e) {
                out.innerText = 'Execution Failed: ' + e.message;
            }
        }
    </script>
</body>
</html>"""

@app.get("/", response_class=HTMLResponse)
async def deliverable_dashboard():
    """Renders the client-facing interactive cockpit."""
    functions_html = ""
    for item in MANIFEST:
        if item.get("type") == "function":
            args = item.get("arguments", [])
            args_badge = "".join(f'<span class="px-2 py-0.5 text-xs bg-indigo-50 text-indigo-700 rounded-md border border-indigo-100 mr-1 font-mono">{a}</span>' for a in args)
            args_json = json.dumps(args)
            functions_html += f"""
            <div class="p-5 bg-white border border-slate-200 rounded-xl shadow-xs hover:border-indigo-200 transition-all">
                <div class="flex items-center justify-between mb-2">
                    <span class="text-xs font-semibold uppercase tracking-wider text-slate-400 font-mono">{item['module']}.py</span>
                    <span class="px-2 py-0.5 text-xs font-medium bg-emerald-50 text-emerald-700 rounded-full border border-emerald-100">Live Method</span>
                </div>
                <h3 class="text-lg font-bold text-slate-900 font-mono mb-1">{item['name']}()</h3>
                <p class="text-sm text-slate-600 mb-4">{item['docstring']}</p>
                <div class="mb-4">
                    <span class="text-xs font-semibold text-slate-500 block mb-1">Accepted Parameters:</span>
                    <div>{args_badge or '<span class="text-xs text-slate-400 italic">No parameters</span>'}</div>
                </div>
                <button onclick='fillRunner("{item["module"]}", "{item["name"]}", {args_json})'
                        class="w-full py-2 px-3 bg-slate-900 hover:bg-indigo-600 text-white text-xs font-semibold rounded-lg transition-colors shadow-xs">
                    Configure & Execute &rarr;
                </button>
            </div>
            """
        elif item.get("type") == "class":
            methods = item.get("methods", [])
            methods_badge = "".join(f'<span class="px-2 py-0.5 text-xs bg-purple-50 text-purple-700 rounded-md border border-purple-100 mr-1 font-mono">{m}()</span>' for m in methods)
            functions_html += f"""
            <div class="p-5 bg-white border border-slate-200 rounded-xl shadow-xs hover:border-purple-200 transition-all">
                <div class="flex items-center justify-between mb-2">
                    <span class="text-xs font-semibold uppercase tracking-wider text-slate-400 font-mono">{item['module']}.py</span>
                    <span class="px-2 py-0.5 text-xs font-medium bg-purple-50 text-purple-700 rounded-full border border-purple-100">Domain Class</span>
                </div>
                <h3 class="text-lg font-bold text-slate-900 font-mono mb-1">{item['name']}</h3>
                <p class="text-sm text-slate-600 mb-4">{item['docstring']}</p>
                <div class="mb-4">
                    <span class="text-xs font-semibold text-slate-500 block mb-1">Declared Methods:</span>
                    <div>{methods_badge or '<span class="text-xs text-slate-400 italic">No methods</span>'}</div>
                </div>
                <button onclick='fillRunner("{item["module"]}", "{item["name"]}", [])'
                        class="w-full py-2 px-3 bg-purple-900 hover:bg-purple-700 text-white text-xs font-semibold rounded-lg transition-colors shadow-xs">
                    Instantiate Class &rarr;
                </button>
            </div>
            """

    if not functions_html:
        functions_html = '<p class="text-sm text-slate-500 italic p-4 bg-white rounded-lg border border-slate-200">Standard API endpoints registered. Use Swagger UI to execute.</p>'

    return HTML_TEMPLATE.replace("__FUNCTIONS_HTML__", functions_html)

@app.post("/api/execute")
async def execute_dynamic_function(req: ExecutionRequest):
    """Executes arbitrary validated domain functions within the delivered package."""
    try:
        mod = sys.modules.get(req.module)
        if mod is None:
            spec = importlib.util.find_spec(req.module)
            if spec is None:
                raise HTTPException(status_code=404, detail=f"Module {req.module} not found.")
            mod = importlib.util.module_from_spec(spec)
            sys.modules[req.module] = mod
            spec.loader.exec_module(mod)

        func_or_class = getattr(mod, req.target, None)
        if func_or_class is None:
            raise HTTPException(status_code=404, detail=f"Target {req.target} not found in {req.module}.")

        if inspect.isclass(func_or_class):
            instance = func_or_class(**req.payload)
            return {"status": "success", "result": f"Instantiated class {req.target} successfully.", "attributes": dir(instance)}

        if callable(func_or_class):
            result = func_or_class(**req.payload)
            # Handle un-serializable returns
            if hasattr(result, "to_dict"):
                result = result.to_dict()
            elif hasattr(result, "dict"):
                result = result.dict()
            elif hasattr(result, "model_dump"):
                result = result.model_dump()
            return {"status": "success", "function": req.target, "result": result}

    except Exception as e:
        return JSONResponse(
            status_code=500,
            content={"status": "error", "error": str(e), "traceback": traceback.format_exc()}
        )

@app.get("/api/contract")
async def get_contract():
    return {"manifest": MANIFEST, "readme": RAW_README}
